### ISSUE TITLE
Would you be interested to use github.com/achiku/varfmt?

### ISSUE THREAD

**Issue by achiku** [shirou/db2structs#1]
Hi, this looks really neat project, and would love to use for our current project. 

I was looking at your code, and noticed that only `id` can be capitalized for field names. Would you be interested to use [varfmt](https://github.com/achiku/varfmt) so that it'll be easier to format field names following go naming convention. 

If you are interested, just let me know. I will create quick pr for this :)

**Comment by shirou** [comment]
Agree. I will introduce more golint-aware name. Thank you for your suggestion.

(BTW, I think [golint](https://github.com/golang/lint/blob/master/lint.go#L649) is a original for Initialisms)

**Comment by achiku** [comment]
Ah, I didn't know the original code is from golint! It seems like you already implemented this function in `name.go`, so I close this issue.
